<?php
/**
 * * NR le 24/12/2020
 *   
 **/ 
$id = $_SESSION['id'];

$req1="SELECT STAGE.ID_STAGE,STAGE.DATE_DEBUT,STAGE.DATE_FIN,ENTREPRISE.NOM_ENTREPRISE,SALARIE.ID_SALARIE,ETUDIANT.NOM_ETUDIANT
        FROM STAGE
        INNER JOIN ETUDIANT ON STAGE.ID_ETUDIANT = ETUDIANT.ID_ETUFIANT
        INNER JOIN SALARIE ON STAGE.ID_SALARIE = SALARIE.ID_SALARIE
        INNER JOIN ENTREPRISE ON SALARIE.ID_ENTREPRISE = ENTREPRISE.ID_ENTREPRISE
        WHERE ETUDIANT.ID_ETUDIANT = :id AND STAGE.ETAT = 'OK'";
$stmt = $db->prepare($req1);
$stmt -> bindValue(":id",$id);
$stmt->execute(); 
$stage = $stmt->fetchAll(PDO::FETCH_BOTH);
?>

<?php 

$id = $_SESSION['id'];

$req1 = "SELECT DATE_DEBUT,DATE_FIN,NOM_ENTREPRISE,PRENOM_SALARIE,PRENOM_ETUDIANT
FROM STAGE
INNER JOIN ETUDIANT ON STAGE.ID_ETUDIANT = ETUDIANT.ID_ETUFIANT
INNER JOIN SALARIE ON STAGE.ID_SALARIE = SALARIE.ID_SALARIE
INNER JOIN ENTREPRISE ON SALARIE.ID_ENTREPRISE = ENTREPRISE.ID_ENTREPRISE
WHERE ETUDIANT.ID_ETUDIANT = :id";
$stmt = $db->prepare($req1);
$stmt -> bindValue(":id",$id);
$stmt->execute(); 
$liste_stage = $stmt->fetchAll(PDO::FETCH_BOTH);
?>